workflows:
  despia-app-builder:
    name: Despia Cloud Web App Builder
    instance_type: mac_mini_m2
    max_build_duration: 30
    cache:
      cache_paths:
        - $CM_BUILD_DIR/node_modules
    environment:
      groups:
        - webapp_secrets
      vars:
        CLIENT_ID: $CLIENT_ID
        CLIENT_ASSET_URL: $CLIENT_ASSET_URL
        CALLBACK_URL: $CALLBACK_URL
      node: latest
      npm: latest

    scripts:
      - name: Install Dependencies
        script: |
          #!/bin/bash
          # Install build dependencies
          brew install jq
          npm install -g npm@latest yarn@latest
          
          # Create callback utilities
          cat > /tmp/callback_functions.sh << 'CALLBACK_EOF'
          #!/bin/bash
          export CM_ARTIFACT_URL="https://app.codemagic.io/app/$CM_APP_ID/build/$CM_BUILD_ID/artifacts"
          
          send_callback() {
            local status=$1
            local message=$2
            local output_url=${3:-}
            
            echo "Sending $status callback to $CALLBACK_URL"
            JSON_PAYLOAD=$(jq -n \
              --arg bid "$CM_BUILD_ID" \
              --arg cid "$CLIENT_ID" \
              --arg url "$output_url" \
              --arg stat "$status" \
              --arg msg "$message" \
              '{build_id: $bid, client_id: $cid, output_url: $url, status: $stat, message: $msg}')
            
            MAX_RETRIES=5
            DELAY=2
            for i in $(seq 1 $MAX_RETRIES); do
              echo "Attempt $i: Sending callback"
              curl -fs -H "Content-Type: application/json" --data "$JSON_PAYLOAD" "$CALLBACK_URL" && return 0
              echo "Callback failed. Retrying in $DELAY seconds..."
              sleep $DELAY
              DELAY=$((DELAY * 2))
            done
            echo "ERROR: Failed to send callback after $MAX_RETRIES attempts"
            return 1
          }
          
          send_failure_callback() {
            send_callback "failed" "$1" ""
            exit 1
          }
          
          export -f send_callback send_failure_callback
          CALLBACK_EOF
          
          chmod +x /tmp/callback_functions.sh
          EOF
          echo "Callback functions prepared and saved to /tmp/callback_functions.sh."
          
      - name: Fetch Source Code
        script: |
          #!/bin/bash
          source /tmp/callback_functions.sh || send_failure_callback "Failed to source callback functions"
          
          echo "Processing Build: $CM_BUILD_ID for Client: $CLIENT_ID"
          WORKSPACE_DIR="/workspace"
          mkdir -p "$WORKSPACE_DIR"
          cd "$WORKSPACE_DIR"
          
          if [[ "$SOURCE_URL" =~ \.git$ ]]; then
            send_callback "in_progress" "Cloning Git repository..."
            git clone "$SOURCE_URL" . || send_failure_callback "Git clone failed"
            
            if [ -n "$SOURCE_BRANCH" ]; then
              git checkout "$SOURCE_BRANCH" || send_failure_callback "Branch checkout failed: $SOURCE_BRANCH"
            fi
          else
            send_callback "in_progress" "Downloading source ZIP..."
            curl -L "$SOURCE_URL" -o source.zip || send_failure_callback "ZIP download failed"
            unzip source.zip || send_failure_callback "ZIP extraction failed"
            rm source.zip
          fi
          
          [ -z "$(ls -A $WORKSPACE_DIR)" ] && send_failure_callback "Empty workspace after fetch"
          send_callback "in_progress" "Source code fetched"

      - name: 2. Detect Framework and Build Web Project
        script: |
          #!/bin/bash
          # Load previously defined functions
          . /tmp/callback_functions.sh

          # Ensure we are in the source directory
          cd source || send_failure_callback "Failed to navigate into source directory."
          
          # Handle common case where zip/clone results in a single sub-directory (flatten structure)
          if [[ $(find . -maxdepth 1 -mindepth 1 -type d | wc -l) -eq 1 ]]; then
              DIR_TO_MOVE=$(find . -maxdepth 1 -mindepth 1 -type d)
              echo "Detected single top-level directory ($DIR_TO_MOVE), flattening structure."
              mv "$DIR_TO_MOVE"/* .
              rmdir "$DIR_TO_MOVE"
          fi

          if [ ! -f package.json ]; then
            send_failure_callback "Could not find package.json in the source code root. Cannot determine framework."
          fi

          PACKAGE_CONTENT=$(cat package.json)
          FRAMEWORK=""
          DIST_FOLDER=""

          # Logic to detect common web frameworks
          if echo "$PACKAGE_CONTENT" | grep -q '"next"'; then
            FRAMEWORK="Next.js"
            DIST_FOLDER=".next"
          elif echo "$PACKAGE_CONTENT" | grep -q '"react"' && echo "$PACKAGE_CONTENT" | grep -q '"react-scripts"'; then
            FRAMEWORK="CRA-React"
            DIST_FOLDER="build"
          elif echo "$PACKAGE_CONTENT" | grep -q '"react"' && echo "$PACKAGE_CONTENT" | grep -q '"vite"'; then
            FRAMEWORK="Vite-React"
            DIST_FOLDER="dist"
          elif echo "$PACKAGE_CONTENT" | grep -q '"vue"'; then
            FRAMEWORK="Vue.js"
            DIST_FOLDER="dist"
          else
            send_failure_callback "Unsupported framework detected. Only Next.js, React, and Vue.js are supported."
          fi

          echo "Detected Framework: $FRAMEWORK."

          # --- ENHANCED BUILD LOGIC WITH FALLBACK ---
          BUILD_SUCCESS=0
          
          # 1. Attempt standard 'npm run build' first
          echo "Attempting standard build: npm run build"
          if npm run build; then
            echo "Standard 'npm run build' successful."
            BUILD_SUCCESS=1
          else
            echo "Standard 'npm run build' failed (Missing script or execution error). Trying framework-specific fallback..."
            
            # 2. Try framework-specific fallback commands using npx
            case "$FRAMEWORK" in
              "Next.js")
                echo "Trying 'npx next build'..."
                if npx next build; then BUILD_SUCCESS=1; fi
                ;;
              "CRA-React")
                echo "Trying 'npx react-scripts build'..."
                if npx react-scripts build; then BUILD_SUCCESS=1; fi
                ;;
              "Vite-React"|"Vue.js")
                echo "Trying 'npx vite build'..."
                if npx vite build; then BUILD_SUCCESS=1; fi
                ;;
              *)
                echo "No framework-specific fallback available."
                ;;
            esac
          fi
          
          # Check if the build ultimately failed
          if [ $BUILD_SUCCESS -eq 0 ]; then
            send_failure_callback "Build failed for $FRAMEWORK project. The 'build' script is missing and framework-specific fallbacks also failed."
          fi
          # --- END ENHANCED BUILD LOGIC ---

          
          # Check for the distribution folder existence
          if [ ! -d $DIST_FOLDER ]; then
            send_failure_callback "Build succeeded, but the expected distribution folder ($DIST_FOLDER) was not found."
          fi
          
          # Save the detected folder name to a temporary file for the publishing step
          echo $DIST_FOLDER > /tmp/dist_folder_name.txt 
          
          echo "Web project built successfully. Distribution folder: $DIST_FOLDER"


    # Artifacts section: Tells Codemagic what file to upload and make available
    artifacts:
      - web-app-dist.zip
    
    publishing:
      scripts:
        - name: 3. Zip Artifact and Final Success Callback
          script: |
            #!/bin/bash
            # Load previously defined functions
            . /tmp/callback_functions.sh

            # Ensure we are in the source directory to access the distribution folder
            cd source || send_failure_callback "Failed to navigate into source directory for zipping."
            
            # Load the detected distribution folder name from /tmp
            DIST_FOLDER=$(cat /tmp/dist_folder_name.txt)
            OUTPUT_ZIP_NAME="web-app-dist.zip"
            
            echo "Zipping the distribution folder ($DIST_FOLDER) into $OUTPUT_ZIP_NAME..."
            
            # Zip the contents of the distribution folder. 
            # We move the zip file one directory up (to the root of the build) 
            # so Codemagic finds it easily based on the 'artifacts' setting.
            if ! zip -r "../$OUTPUT_ZIP_NAME" "$DIST_FOLDER"; then
              echo "ERROR: Failed to zip the distribution folder $DIST_FOLDER."
              exit 1
            fi
            
            echo "Artifact successfully created: $OUTPUT_ZIP_NAME"
            
            # Send the final success callback.
            send_callback "success" "Build completed, artifact successfully published." "$CM_ARTIFACT_URL"
            
            echo "Final callback finished."